BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.auth_user_directory (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL UNIQUE,
  role text,
  school_id uuid REFERENCES public.schools(id) ON DELETE SET NULL,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.auth_user_directory ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.auth_user_directory FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.auth_user_directory TO service_role;

CREATE OR REPLACE FUNCTION public.sync_auth_user_directory_from_auth()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  IF NEW.email IS NULL THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.auth_user_directory (user_id, email, is_active, updated_at)
  VALUES (NEW.id, lower(NEW.email)::text, NEW.deleted_at IS NULL, now())
  ON CONFLICT (user_id) DO UPDATE
  SET email = EXCLUDED.email,
      is_active = EXCLUDED.is_active,
      updated_at = now();

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_auth_user_directory_from_auth ON auth.users;
CREATE TRIGGER trg_sync_auth_user_directory_from_auth
AFTER INSERT OR UPDATE OF email, deleted_at ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.sync_auth_user_directory_from_auth();

CREATE OR REPLACE FUNCTION public.sync_auth_user_directory_from_profile()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.auth_user_directory
  SET role = NEW.role,
      school_id = NEW.school_id,
      updated_at = now()
  WHERE user_id = NEW.id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_auth_user_directory_from_profile ON public.profiles;
CREATE TRIGGER trg_sync_auth_user_directory_from_profile
AFTER INSERT OR UPDATE OF role, school_id ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.sync_auth_user_directory_from_profile();

INSERT INTO public.auth_user_directory (user_id, email, role, school_id, is_active, updated_at)
SELECT
  users.id,
  lower(users.email)::text,
  profiles.role,
  profiles.school_id,
  users.deleted_at IS NULL,
  now()
FROM auth.users AS users
LEFT JOIN public.profiles AS profiles ON profiles.id = users.id
WHERE users.email IS NOT NULL
ON CONFLICT (user_id) DO UPDATE
SET email = EXCLUDED.email,
    role = EXCLUDED.role,
    school_id = EXCLUDED.school_id,
    is_active = EXCLUDED.is_active,
    updated_at = now();

CREATE TABLE IF NOT EXISTS public.password_reset_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  school_id uuid REFERENCES public.schools(id) ON DELETE SET NULL,
  role text,
  email text NOT NULL,
  code_hash text NOT NULL,
  requested_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  last_attempt_at timestamptz,
  verified_at timestamptz,
  reset_token_hash text,
  reset_token_expires_at timestamptz,
  processing_at timestamptz,
  processing_lock text,
  consumed_at timestamptz,
  completed_at timestamptz,
  delivery_status text NOT NULL DEFAULT 'pending' CHECK (delivery_status IN ('pending', 'sent', 'failed', 'superseded')),
  delivered_at timestamptz,
  delivery_error text,
  request_ip_hash text,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_password_reset_requests_email_requested
  ON public.password_reset_requests (email, requested_at DESC);
CREATE INDEX IF NOT EXISTS idx_password_reset_requests_user
  ON public.password_reset_requests (user_id, requested_at DESC);
CREATE INDEX IF NOT EXISTS idx_password_reset_requests_active
  ON public.password_reset_requests (email, verified_at DESC)
  WHERE consumed_at IS NULL;

ALTER TABLE public.password_reset_requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.password_reset_requests FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.password_reset_requests TO service_role;

CREATE TABLE IF NOT EXISTS public.password_reset_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid REFERENCES public.password_reset_requests(id) ON DELETE SET NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  school_id uuid REFERENCES public.schools(id) ON DELETE SET NULL,
  role text,
  email text NOT NULL,
  event_type text NOT NULL,
  request_ip_hash text,
  user_agent text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_password_reset_audit_email_created
  ON public.password_reset_audit (email, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_password_reset_audit_school_created
  ON public.password_reset_audit (school_id, created_at DESC);

ALTER TABLE public.password_reset_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.password_reset_audit FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.password_reset_audit TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.password_reset_audit_id_seq TO service_role;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS last_password_reset_at timestamptz,
  ADD COLUMN IF NOT EXISTS password_reset_count integer NOT NULL DEFAULT 0;

ALTER TABLE public.schools
  ADD COLUMN IF NOT EXISTS last_password_reset_at timestamptz;

COMMENT ON TABLE public.password_reset_requests IS 'Server-only one-time password recovery requests. Contains hashes, never plaintext codes or passwords.';
COMMENT ON TABLE public.password_reset_audit IS 'Server-only audit trail for Campus Desk password recovery events.';
COMMENT ON COLUMN public.profiles.last_password_reset_at IS 'Timestamp only; Campus Desk never stores or displays plaintext passwords.';

COMMIT;
